// Multilanguage support - header file

#define		LANG_STR_CNT		109

bool lang_loadfromfile(LPWSTR lpFileName);
void lang_loaddefaults();
LPWSTR _str(DWORD index);
void lang_init();
void lang_destroy();
bool lang_getname(LPWSTR lpFileName, LPWSTR lpNameOut);

#define          STR_LANGUAGE          0
#define          STR_MEDIABROWSER      1
#define          STR_SHUFFLE           2
#define          STR_REPEAT            3
#define          STR_SLEEPMODE         4
#define          STR_SETTINGS          5
#define          STR_ABOUT             6
#define          STR_BLANKSCREEN       7
#define          STR_EXIT              8
#define          STR_GENERALSETTINGS   9
#define          STR_FILEASSOCIATIONS  10
#define          STR_LISTSANDBROWSERS  11
#define          STR_EQUALIZER         12
#define          STR_SKINSELECTOR      13
#define          STR_BACKTOPREVIOUSME  14
#define          STR_OK                15
#define          STR_CANCEL            16
#define          STR_OPTIONS           17
#define          STR_PLAYLIST          18
#define          STR_PLAYCURRENTFOLDE  19
#define          STR_APPENDCURRENTFOL  20
#define          STR_PLAYSELECTION     21
#define          STR_APPENDSELECTION   22
#define          STR_RECURSIVESEARCH   23
#define          STR_SELECTALL         24
#define          STR_SELECTNONE        25
#define          STR_INVERTSELECTION   26
#define          STR_BACKTOTHEPLAYER   27
#define          STR_APPENDITEMANDPLA  28
#define          STR_ENQUEUEITEM       29
#define          STR_MINIMIZE          30
#define          STR_BLANK             31
#define          STR_LIBRARY           32
#define          STR_THEPLAYLISTFILES  33
#define          STR_COULDNOTLOADTHES  34
#define          STR_THEREARENOSKINFI  35
#define          STR_NONEOFTHEFILESIN  36
#define          STR_ERROR             37
#define          STR_MESSAGE           38
#define          STR_DELETESELECTED    39
#define          STR_CLEARPLAYLIST     40
#define          STR_GOTOPLAYINGSONG   41
#define          STR_SETASNEXT         42
#define          STR_DELETE            43
#define          STR_MOVEUP            44
#define          STR_MOVEDOWN          45
#define          STR_MOVETO            46
#define          STR_GOTOFOLDER        47
#define          STR_BEFORETHISITEM    48
#define          STR_AFTERTHISITEM     49
#define          STR_SWAP              50
#define          STR_CANCELMOVE        51
#define          STR_THREADPRIORITY    52
#define          STR_LOW               53
#define          STR_NORMAL            54
#define          STR_SLEEPACTION       55
#define          STR_CLOSEAPPLICATION  56
#define          STR_STOPMUSIC         57
#define          STR_PREBUFFERLENGTH   58
#define          STR_OUTPUTPREBUFFER   59
#define          STR_LEFTSOFTKEYACTIO  60
#define          STR_MINIMIZEPLAYER    61
#define          STR_FORCECLEARTYPERE  62
#define          STR_LOCKHARDWAREKEYS  63
#define          STR_CHANGEPLAYINGSON  64
#define          STR_READIDTAGSWHENAV  65
#define          STR_PLAYLISTEDITOR    66
#define          STR_MEDIA             67
#define          STR_PLAYLISTMOVEITEM  68
#define          STR_MINUTES           69
#define          STR_ACTIVE            70
#define          STR_USENITROGENTOOPE  71
#define          STR_IFTHEPLAYERISNOT  72
#define          STR_IFTHEPLAYERISALR  73
#define          STR_ADDFILETOPLAYLIS  74
#define          STR_SETFILEASPLAYLIS  75
#define          STR_SETFOLDERASPLAYL  76
#define          STR_ENABLEKINETICSCR  77
#define          STR_KINETICSCROLLING  78
#define          STR_REFRESHINTERVAL   79
#define          STR_INITIALSPEED      80
#define          STR_DEACCELERATION    81
#define          STR_MINIMALGESTURE    82
#define          STR_LOWERFONTQUALITY  83
#define          STR_GRAPHICEQUALIZER  84
#define          STR_ENABLEEQUALIZER   85
#define          STR_PRESETS           86
#define          STR_ADDASPRESET       87
#define          STR_REMOVEPRESET      88
#define          STR_RESETEQUALIZER    89
#define          STR_ENTERTHENAMEOFTH  90
#define          STR_PLEASEDONATEIFYO  91
#define          STR_MANYTHANKSTOEVER  92
#define          STR_HELPEDMAKETHISPR  93
#define          STR_STABLEANDGOODLOO  94
#define          STR_LANGUAGETRANSLAT  95
#define          STR_BYAUTHOR          96
#define          STR_THEVERSIONOFTHES  97
#define          STR_THESKINFILEWASNO  98
#define          STR_LANGUAGESELECTOR  99
#define          STR_REMEMBERLASTSONG  100
#define          STR_YOURDEVICEHASNOK  101
#define          STR_WRITECURRENTSONG  102
#define          STR_THISFUNCTIONISNO  103
#define          STR_EMPTYPLAYLIST     104
#define          STR_UNKNOWNARTIST     105
#define          STR_STANDBY           106
#define          STR_USESYSTEMVOLUME   107
#define          STR_DISCWAITING       108
